### ISSUE TITLE
hailo_sdk_client.sdk_backend.sdk_backend_exceptions.BackendValueError: Unsupported NaN values were found in params 

### ISSUE THREAD

**Issue by vladbph** [hailo-ai/hailo_model_zoo#136]
Compiling yolov8 `medium` obj detection model caused the error:
    raise BackendValueError(f"Unsupported NaN values were found in params {not_good_params}")

hailo_sdk_client.sdk_backend.sdk_backend_exceptions.BackendValueError: Unsupported NaN values were found in params ['yolov8m/conv1/kernel:0', 'yolov8m/conv11/kernel:0', 'yolov8m/conv12/kernel:0', 'yolov8m/conv13/kernel:0', 'yolov8m/conv14/kernel:0', 'yolov8m/conv15/kernel:0', 'yolov8m/conv16/kernel:0', 'yolov8m/conv17/kernel:0', 'yolov8m/conv18/kernel:0', 'yolov8m/conv19/kernel:0', 'yolov8m/conv2/kernel:0', 'yolov8m/conv20/kernel:0', 'yolov8m/conv22/kernel:0', 'yolov8m/conv23/kernel:0', 'yolov8m/conv24/kernel:0', 'yolov8m/conv25/kernel:0', 'yolov8m/conv26/kernel:0', 'yolov8m/conv27/kernel:0', 'yolov8m/conv28/kernel:0', 'yolov8m/conv29/kernel:0', 'yolov8m/conv30/kernel:0', 'yolov8m/conv31/kernel:0', 'yolov8m/conv33/kernel:0', 'yolov8m/conv34/kernel:0', 'yolov8m/conv35/kernel:0', 'yolov8m/conv36/kernel:0', 'yolov8m/conv37/kernel:0', 'yolov8m/conv38/kernel:0', 'yolov8m/conv39/kernel:0', 'yolov8m/conv4/kernel:0', 'yolov8m/conv41/kernel:0', 'yolov8m/conv42/kernel:0', 'yolov8m/conv43/kernel:0', 'yolov8m/conv44/kernel:0', 'yolov8m/conv45/kernel:0', 'yolov8m/conv47/kernel:0', 'yolov8m/conv48/kernel:0', 'yolov8m/conv49/kernel:0', 'yolov8m/conv5/kernel:0', 'yolov8m/conv50/kernel:0', 'yolov8m/conv51/kernel:0', 'yolov8m/conv52/kernel:0', 'yolov8m/conv53/kernel:0', 'yolov8m/conv54/kernel:0', 'yolov8m/conv55/kernel:0', 'yolov8m/conv56/kernel:0', 'yolov8m/conv57/kernel:0', 'yolov8m/conv58/kernel:0', 'yolov8m/conv6/kernel:0', 'yolov8m/conv60/kernel:0', 'yolov8m/conv61/kernel:0', 'yolov8m/conv62/kernel:0', 'yolov8m/conv63/kernel:0', 'yolov8m/conv64/kernel:0', 'yolov8m/conv65/kernel:0', 'yolov8m/conv66/kernel:0', 'yolov8m/conv67/kernel:0', 'yolov8m/conv68/kernel:0', 'yolov8m/conv69/kernel:0', 'yolov8m/conv7/kernel:0', 'yolov8m/conv70/kernel:0', 'yolov8m/conv71/kernel:0', 'yolov8m/conv73/kernel:0', 'yolov8m/conv74/kernel:0', 'yolov8m/conv75/kernel:0', 'yolov8m/conv76/kernel:0', 'yolov8m/conv77/kernel:0', 'yolov8m/conv78/kernel:0', 'yolov8m/conv79/kernel:0', 'yolov8m/conv8/kernel:0', 'yolov8m/conv80/kernel:0', 'yolov8m/conv81/kernel:0', 'yolov8m/conv82/kernel:0', 'yolov8m/conv83/kernel:0', 'yolov8m/conv9/kernel:0', 'yolov8m/conv_feature_splitter1_1/kernel:0', 'yolov8m/conv_feature_splitter1_2/kernel:0', 'yolov8m/conv_feature_splitter2_1/kernel:0', 'yolov8m/conv_feature_splitter2_2/kernel:0', 'yolov8m/conv_feature_splitter3_1/kernel:0', 'yolov8m/conv_feature_splitter3_2/kernel:0', 'yolov8m/conv_feature_splitter4_1/kernel:0', 'yolov8m/conv_feature_splitter4_2/kernel:0', 'yolov8m/conv_feature_splitter5_1/kernel:0', 'yolov8m/conv_feature_splitter5_2/kernel:0', 'yolov8m/conv_feature_splitter6_1/kernel:0', 'yolov8m/conv_feature_splitter6_2/kernel:0', 'yolov8m/conv_feature_splitter7_1/kernel:0', 'yolov8m/conv_feature_splitter7_2/kernel:0', 'yolov8m/conv_feature_splitter8_1/kernel:0', 'yolov8m/conv_feature_splitter8_2/kernel:0', 'yolov8m/normalization1/kernel:0']

Small model compilation works just fine

**Comment by jake-is-ESD-protected** [comment]
I have the same error for a small custom model. Happens when running `hailo optimize --use-random-calib-set model.har`

**Version:** Hailo Dataflow Compiler v3.30.0  
**Installation method:** Hailo Software Suite docker container
**Machine:** x86_64 with NVIDIA GPUs

### Logs
```bash
[info] Current Time: 09:48:22, 01/10/25
[info] CPU: Architecture: x86_64, Model: Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz, Number Of Cores: 48, Utilization: 0.5%
[info] Memory: Total: 251GB, Available: 246GB
[info] System info: OS: Linux, Kernel: 5.4.0-204-generic
[info] Hailo DFC Version: 3.30.0
[info] HailoRT Version: 4.20.0
[info] PCIe: No Hailo PCIe device was found
[info] Running `hailo -V`
```

### Traceback
```
Traceback (most recent call last):
  File "/local/workspace/hailo_virtualenv/bin/hailo", line 8, in <module>
    sys.exit(main())
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_client/tools/cmd_utils/main.py", line 111, in main
    ret_val = client_command_runner.run()
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_platform/tools/hailocli/main.py", line 64, in run
    ret_val = self._run(argv)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_platform/tools/hailocli/main.py", line 111, in _run
    return args.func(args)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_client/tools/optimize_cli.py", line 120, in run
    self._runner.optimize(dataset, work_dir=args.work_dir)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_common/states/states.py", line 16, in wrapped_func
    return func(self, *args, **kwargs)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_client/runner/client_runner.py", line 2128, in optimize
    self._optimize(calib_data, data_type=data_type, work_dir=work_dir)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_common/states/states.py", line 16, in wrapped_func
    return func(self, *args, **kwargs)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_client/runner/client_runner.py", line 1970, in _optimize
    self._sdk_backend.full_quantization(calib_data, data_type=data_type, work_dir=work_dir)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 1125, in full_quantization
    self._full_acceleras_run(self.calibration_data, data_type)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 1321, in _full_acceleras_run
    self.save_and_load_params_hailo_optimized(fp_after_optimization)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 1140, in save_and_load_params_hailo_optimized
    self.load_params(params, ParamsKinds.HAILO_OPTIMIZED)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 515, in load_params
    return super().load_params(params, params_kind=params_kind)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 231, in load_params
    self._validate_params(params_to_load, params_kind)
  File "/local/workspace/hailo_virtualenv/lib/python3.10/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 298, in _validate_params
    raise BackendValueError(f"Unsupported NaN values were found in params {not_good_params}")
hailo_sdk_client.sdk_backend.sdk_backend_exceptions.BackendValueError: Unsupported NaN values were found in params ['cnn2-17-0_0467-0_00_keras_float32/conv1/bias:0', 'cnn2-17-0_0467-0_00_keras_float32/conv1/kernel:0', 'cnn2-17-0_0467-0_00_keras_float32/conv2/bias:0', 'cnn2-17-0_0467-0_00_keras_float32/conv2/kernel:0', 'cnn2-17-0_0467-0_00_keras_float32/conv3/bias:0', 'cnn2-17-0_0467-0_00_keras_float32/conv3/kernel:0', 'cnn2-17-0_0467-0_00_keras_float32/conv4/bias:0', 'cnn2-17-0_0467-0_00_keras_float32/conv4/kernel:0', 'cnn2-17-0_0467-0_00_keras_float32/conv5/bias:0', 'cnn2-17-0_0467-0_00_keras_float32/conv5/kernel:0', 'cnn2-17-0_0467-0_00_keras_float32/conv6/bias:0', 'cnn2-17-0_0467-0_00_keras_float32/conv6/kernel:0', 'cnn2-17-0_0467-0_00_keras_float32/conv7/bias:0', 'cnn2-17-0_0467-0_00_keras_float32/conv7/kernel:0']
```

### Odd thing I noticed
In case of model conversion without GPU support, I of course get the warning `WARNING - mo_config.py:166 - Reducing optimization level to 0 (the accuracy won't be optimized and compression won't be used) because there's no available GPU` but the process actually finishes, indicating that the `NaN` values are only an issue to a process deeper down the pipeline.
