### ISSUE TITLE
Error: Model uses too many reources: 136 Layer-Controllers

### ISSUE THREAD

**Issue by frenky-strasak** [hailo-ai/hailo_model_zoo#33]
```
onnx: 1.11.0
torch: 1.12.1
torchvision: 0.13.1
```

Hi,
I have fine-tuned **yolov5m_wo_spp.pt** model in the **yolov5 v6.2** framework. Then I have exported the model to onnx (with opset 11) also in the **yolov5 v6.2** framework.
When I compile this onnx model with ```hailomz compile```, the  model optimization is done correctly, but then it throws following error:
```
997/1000 [============================>.] - ETA: 1s - total_distill_loss: 0.1018 - _distill_loss_yolov5m_wo_spp/conv93: 0.0353 - _distill_loss_yolov5m_wo_spp/conv84: 0.0367 - _distill_loss_yolov5m_wo_spp/conv74 998/1000 [============================>.] - ETA: 0s - total_distill_loss: 0.1018 - _distill_loss_yolov5m_wo_spp/conv93: 0.0353 - _distill_loss_yolov5m_wo_spp/conv84: 0.0367 - _distill_loss_yolov5m_wo_spp/conv74 999/1000 [============================>.] - ETA: 0s - total_distill_loss: 0.1018 - _distill_loss_yolov5m_wo_spp/conv93: 0.0353 - _distill_loss_yolov5m_wo_spp/conv84: 0.0367 - _distill_loss_yolov5m_wo_spp/conv741000/1000 [==============================] - ETA: 0s - total_distill_loss: 0.1018 - _distill_loss_yolov5m_wo_spp/conv93: 0.0353 - _distill_loss_yolov5m_wo_spp/conv84: 0.0367 - _distill_loss_yolov5m_wo_spp/conv741000/1000 [==============================] - 477s 477ms/step - total_distill_loss: 0.1018 - _distill_loss_yolov5m_wo_spp/conv93: 0.0353 - _distill_loss_yolov5m_wo_spp/conv84: 0.0367 - _distill_loss_yolov5m_wo_spp/conv74: 0.0297
[info] Fine Tune is done (completion time is 00:38:18.70)
Calibration: 64entries [00:48,  1.32entries/s]

[info] Model Optimization is done
[info] Loading model script on yolov5m_wo_spp
[info] Loading network parameters
[info] Starting Hailo allocation and compilation flow
[info] Using Single-context flow
[info] Resources optimization guidelines: Strategy -> GREEDY Objective -> REQUIRED_FPS
[info] Resources optimization params: max_control_utilization=120%, max_compute_utilization=100%, max_memory_utilization (weights)=100%, max_input_aligner_utilization=100%, max_apu_utilization=100%
[info] Running Auto-Merger
[info] Auto-Merger is done
[info] Adding a portal between conv27( index=19 604, name=conv27, ) and concat7, type: L4
[info] Starting context partition
[info] Context partition is done (0s 2ms)
[info] Adding format conversion layer 'auto_reshape_from_input_layer1_to_merged_layer_normalization1_space_to_depth1' after input_layer1
[info] Adding format conversion layer 'auto_reshape_from_conv74_to_output_layer1' after conv74
[info] Adding format conversion layer 'auto_reshape_from_conv84_to_output_layer2' after conv84
[info] Adding format conversion layer 'auto_reshape_from_conv93_to_output_layer3' after conv93
Model uses too many reources: 136 Layer-Controllers
[critical] Model uses too many reources: 136 Layer-Controllers
[error] Failed to produce compiled graph
[error] Tried to deserialize allocator result on failure, but got another exception: No output graph, deserialization failed.
Traceback (most recent call last):
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/bin/hailomz", line 33, in <module>
    sys.exit(load_entry_point('hailo-model-zoo', 'console_scripts', 'hailomz')())
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/sources/model_zoo/hailo_model_zoo/main.py", line 181, in main
    run(args)
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/sources/model_zoo/hailo_model_zoo/main.py", line 170, in run
    return handlers[args.command](args)
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/sources/model_zoo/hailo_model_zoo/main_driver.py", line 132, in compile
    compile_model(runner, network_info, args.results_dir, model_script_path=args.model_script_path)
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/sources/model_zoo/hailo_model_zoo/core/main_utils.py", line 298, in compile_model
    hef = runner.compile()
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/lib/python3.8/site-packages/hailo_sdk_common/states/states.py", line 16, in wrapped_func
    return func(self, *args, **kwargs)
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/lib/python3.8/site-packages/hailo_sdk_client/runner/client_runner.py", line 661, in compile
    return self._get_hef_hw_representation()
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/lib/python3.8/site-packages/hailo_sdk_common/states/states.py", line 16, in wrapped_func
    return func(self, *args, **kwargs)
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/lib/python3.8/site-packages/hailo_sdk_client/runner/client_runner.py", line 707, in _get_hef_hw_representation
    serialized_hef = self._sdk_backend.get_hef_hw_representation(fps, allocator_script, mapping_timeout)
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/lib/python3.8/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 1156, in get_hef_hw_representation
    hef, mapped_graph_file = self._get_hef_hw_representation(fps, allocator_script, mapping_timeout)
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/lib/python3.8/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 1151, in _get_hef_hw_representation
    hef, mapped_graph_file, auto_alls = self.hef_full_build(fps, mapping_timeout, model_params, allocator_script)
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/lib/python3.8/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 1128, in hef_full_build
    auto_alls, self._mapped_graph, self._integrated_graph = allocator.create_mapping_and_full_build_hef(
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/lib/python3.8/site-packages/hailo_sdk_client/allocator/hailo_tools_runner.py", line 568, in create_mapping_and_full_build_hef
    self.call_builder(network_graph_path, output_path, compilation_output_proto=compilation_output_proto,
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/lib/python3.8/site-packages/hailo_sdk_client/allocator/hailo_tools_runner.py", line 527, in call_builder
    self.run_builder(network_graph_path, output_path, **kwargs)
  File "/home/user/Documents/programs/hailo/2022_09/hailo_sw_suite/hailo_venv/lib/python3.8/site-packages/hailo_sdk_client/allocator/hailo_tools_runner.py", line 394, in run_builder
    raise e.internal_exception("Hailo tools builder failed:", hailo_tools_error=e.hailo_tools_error) from None
hailo_sdk_client.sdk_backend.sdk_backend_exceptions.BackendAllocatorException: Hailo tools builder failed: Model uses too many reources: 136 Layer-Controllers
```
If I train the model in the hailo yolov5 retraining docker container, the compilation works fine.
Any idea what this error means?

**Comment by frenky-strasak** [comment]
I can also compile the default ```yolov5m_wo_spp.pt``` model exported to onnx using the **yolov5 v6.2 framework**. This error only occurs if I use ```yolov5m_wo_spp.pt``` model trained (fine-tuned) in **yolov5 v6.2 framework**.

**Comment by nadaved1** [comment]
Hi Frenky,
The retraining docker is forked out of the tag v2 of YOLOV5. In between v2
and v6, each network variant have become bigger with more ops.
This means that the compilation of v6 looks a bit different than the v2
one. If you'll notice we also support v6.1 in the model-zoo, specifically
you can check the alls file for this net.
https://github.com/hailo-ai/hailo_model_zoo/blob/master/hailo_model_zoo/cfg/alls/yolov5m_6.1.alls

If you want/need dedicated support for converting this net, you're welcome
to open a support ticket at hailo.ai

בתאריך יום ג׳, 15 בנוב׳ 2022, 16:14, מאת Frenky Střasák ‏<
***@***.***>:

**Comment by frenky-strasak** [comment]
Thank you, I will try it.
