### ISSUE TITLE
yolov5 compile error

### ISSUE THREAD

**Issue by ryangsookim** [hailo-ai/hailo_model_zoo#78]
Hi,

I'm encountering errors when attempting to compile pretrained yolov5m_wo_spp.onnx using hailomz. Here are the details:

Command:

> hailomz compile --ckpt ../models/yolov5m_wo_spp.onnx  --calib-path /local/shared_with_docker/rskim_model_compiler/datasets/coco/images/train2017/ --yaml yolov5m_wo_spp.yaml 

Error Messages:

> [info] First time Hailo Dataflow Compiler is being used. Checking system requirements... (this might take a few seconds)
[Info] No GPU connected.
In file included from /local/workspace/hailo_virtualenv/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1948,
                 from /local/workspace/hailo_virtualenv/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /local/workspace/hailo_virtualenv/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /home/hailo/.pyxbld/temp.linux-x86_64-cpython-38/local/workspace/hailo_model_zoo/hailo_model_zoo/core/postprocessing/cython_utils/cython_nms.c:1173:
/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
Traceback (most recent call last):
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 314, in create_module
    so_path = build_module(spec.name, pyxfilename=spec.origin, pyxbuild_dir=self._pyxbuild_dir,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 197, in build_module
    so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/pyxbuild.py", line 144, in pyx_to_dll
    raise ImportError("reload count for %s reached maximum" % org_path)
ImportError: reload count for /home/hailo/.pyxbld/lib.linux-x86_64-cpython-38/hailo_model_zoo/core/postprocessing/cython_utils/cython_nms.cpython-38-x86_64-linux-gnu.so reached maximum
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/local/workspace/hailo_virtualenv/bin/hailomz", line 33, in <module>
    sys.exit(load_entry_point('hailo-model-zoo', 'console_scripts', 'hailomz')())
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main.py", line 188, in main
    run(args)
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main.py", line 168, in run
    from hailo_model_zoo.main_driver import parse, optimize, compile, profile, evaluate
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main_driver.py", line 14, in <module>
    from hailo_model_zoo.core.main_utils import (compile_model, get_hef_path, get_integrated_postprocessing,
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/main_utils.py", line 8, in <module>
    from hailo_model_zoo.core.eval import eval_factory
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/eval/eval_factory.py", line 9, in <module>
    from hailo_model_zoo.core.eval.instance_segmentation_evaluation import InstanceSegmentationEval
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/eval/instance_segmentation_evaluation.py", line 8, in <module>
    from hailo_model_zoo.core.eval.instance_segmentation_evaluation_utils import (YolactEval,
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/eval/instance_segmentation_evaluation_utils.py", line 4, in <module>
    from hailo_model_zoo.core.postprocessing.instance_segmentation_postprocessing import _sanitize_coordinates
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/postprocessing/instance_segmentation_postprocessing.py", line 8, in <module>
    from hailo_model_zoo.core.postprocessing.cython_utils.cython_nms import nms as cnms
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 332, in create_module
    raise exc.with_traceback(tb)
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 314, in create_module
    so_path = build_module(spec.name, pyxfilename=spec.origin, pyxbuild_dir=self._pyxbuild_dir,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 197, in build_module
    so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/pyxbuild.py", line 144, in pyx_to_dll
    raise ImportError("reload count for %s reached maximum" % org_path)
ImportError: Building module hailo_model_zoo.core.postprocessing.cython_utils.cython_nms failed: ['ImportError: reload count for /home/hailo/.pyxbld/lib.linux-x86_64-cpython-38/hailo_model_zoo/core/postprocessing/cython_utils/cython_nms.cpython-38-x86_64-linux-gnu.so reached maximum\n']

What's causing these errors, and how can I resolve them?

**Comment by nina-vilela** [comment]
Hi @ryangsookim,

You mentioned that the model is pre-trained. If you mean that you haven't re-trained the model, then you don't have to go through the compilation process. You can instead download an already compiled model [here.](https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ModelZoo/Compiled/v2.10.0/hailo8/yolov5m_wo_spp_60p.hef)

If you have re-trained the model, it is important to notice that the calibration dataset does not need to contain the entire training set. For yolov5m_wo_spp, we use a calibration dataset with size 4000. The error you are facing could be related to using too many images that are not encoded as a tfrecord. Please try again with a folder containing 4000 images and let us know how it goes.

**Comment by ryangsookim** [comment]
Hi @nina-vilela,

'm encountering a persistent error while training and compiling a custom YOLOv5 model. I'm practicing with the HAILO-APPLICATION-CODE-EXAMPLES to test model functionality.

Following your suggestion, I reduced the calibration images to 4,000, but the error occurrs.

> $ python3 create_coco_tfrecord.py calib2017 --img /local/shared_with_docker/rskim_model_compiler/datasets/coco/images/train2017/ --det /local/shared_with_docker/rskim_model_compiler/datasets/coco/annotations/instances_train2017.json --num-images 4000
2024-01-10 09:42:54.887583: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-10 09:42:55.716309: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
1021 / 118287 images have no annotations
calib2017 #4000: /local/shared_with_docker/rskim_model_compiler/datasets/coco/images/train2017/000000088376.jpg: 100%|█| 4000/4000 [00:26<00
Done converting 4000 images

In addition, the error persists even with a single calibration image.

>  python3 create_coco_tfrecord.py calib2017 --img /local/shared_with_docker/rskim_model_compiler/datasets/coco/images/train2017/ --det /local/shared_with_docker/rskim_model_compiler/datasets/coco/annotations/instances_train2017.json --num-images 1
2024-01-10 09:53:04.727553: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-10 09:53:05.567471: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
1021 / 118287 images have no annotations
calib2017 #1: /local/shared_with_docker/rskim_model_compiler/datasets/coco/images/train2017/000000522195.jpg: 100%|█| 1/1 [00:00<00:00, 68.9
Done converting 1 images

> $ hailomz compile --ckpt ../models/yolov5m_wo_spp.onnx  --calib-path /local/shared_with_docker/rskim_model_compiler/datasets/coco/images/train2017/ --yaml yolov5m_wo_spp.yaml
Traceback (most recent call last):
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 314, in create_module
    so_path = build_module(spec.name, pyxfilename=spec.origin, pyxbuild_dir=self._pyxbuild_dir,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 197, in build_module
    so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/pyxbuild.py", line 144, in pyx_to_dll
    raise ImportError("reload count for %s reached maximum" % org_path)
ImportError: reload count for /home/hailo/.pyxbld/lib.linux-x86_64-cpython-38/hailo_model_zoo/core/postprocessing/cython_utils/cython_nms.cpython-38-x86_64-linux-gnu.so reached maximum
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/local/workspace/hailo_virtualenv/bin/hailomz", line 33, in <module>
    sys.exit(load_entry_point('hailo-model-zoo', 'console_scripts', 'hailomz')())
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main.py", line 188, in main
    run(args)
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main.py", line 168, in run
    from hailo_model_zoo.main_driver import parse, optimize, compile, profile, evaluate
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main_driver.py", line 14, in <module>
    from hailo_model_zoo.core.main_utils import (compile_model, get_hef_path, get_integrated_postprocessing,
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/main_utils.py", line 8, in <module>
    from hailo_model_zoo.core.eval import eval_factory
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/eval/eval_factory.py", line 9, in <module>
    from hailo_model_zoo.core.eval.instance_segmentation_evaluation import InstanceSegmentationEval
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/eval/instance_segmentation_evaluation.py", line 8, in <module>
    from hailo_model_zoo.core.eval.instance_segmentation_evaluation_utils import (YolactEval,
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/eval/instance_segmentation_evaluation_utils.py", line 4, in <module>
    from hailo_model_zoo.core.postprocessing.instance_segmentation_postprocessing import _sanitize_coordinates
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/postprocessing/instance_segmentation_postprocessing.py", line 8, in <module>
    from hailo_model_zoo.core.postprocessing.cython_utils.cython_nms import nms as cnms
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 332, in create_module
    raise exc.with_traceback(tb)
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 314, in create_module
    so_path = build_module(spec.name, pyxfilename=spec.origin, pyxbuild_dir=self._pyxbuild_dir,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 197, in build_module
    so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/pyxbuild.py", line 144, in pyx_to_dll
    raise ImportError("reload count for %s reached maximum" % org_path)
ImportError: Building module hailo_model_zoo.core.postprocessing.cython_utils.cython_nms failed: ['ImportError: reload count for /home/hailo/.pyxbld/lib.linux-x86_64-cpython-38/hailo_model_zoo/core/postprocessing/cython_utils/cython_nms.cpython-38-x86_64-linux-gnu.so reached maximum\n']

Here's the content of my YAML file: 

> base:
- base/yolov5.yaml
quantization:
  calib_set:
  - models_files/coco/2023-08-03/coco_calib2017.tfrecord
network:
  network_name: yolov5m_wo_spp
paths:
  alls_script: yolov5m_wo_spp.alls
  network_path:
  - models_files/ObjectDetection/Detection-COCO/yolo/yolov5m/pretrained/2023-04-25/yolov5m_wo_spp.onnx
  url: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ObjectDetection/Detection-COCO/yolo/yolov5m/pretrained/2023-04-25/yolov5m_wo_spp.zip
parser:
  nodes:
  - images
  - - Conv_283
    - Conv_267
    - Conv_251
postprocessing:
  device_pre_post_layers:
    nms: false
  postprocess_config_file: models_files/ObjectDetection/Detection-COCO/yolo/yolov5m/pretrained/2023-04-25/yolov5m_nms_config.json
  meta_arch: yolo
  hpp: false
info:
  input_shape: 640x640x3
  output_shape: 20x20x255, 40x40x255, 80x80x255
  operations: 52.98G
  parameters: 22.67M
  framework: pytorch
  training_data: coco train2017
  validation_data: coco val2017
  eval_metric: mAP
  full_precision_result: 42.46
  source: https://github.com/ultralytics/yolov5/releases/tag/v2.0
  license_url: https://github.com/ultralytics/yolov5/blob/master/LICENSE


Could you please advise on next steps to troubleshoot this issue? I'm eager to resolve it and proceed with model training.

Thank you for your assistance.

**Comment by ryangsookim** [comment]
Hi, @nina-vilela 

I'm encountering a persistent error while training and compiling a custom YOLOv5 model. 

I'm practicing with the HAILO-APPLICATION-CODE-EXAMPLES to test model compilation functionality.

According to your comment, I have tried to create tfrecord file containing 4000 images as follows:

> python3 create_coco_tfrecord.py calib2017 --img /local/shared_with_docker/rskim_model_compiler/datasets/coco/images/train2017/ --det /local/shared_with_docker/rskim_model_compiler/datasets/coco/annotations/instances_train2017.json --num-images 4000
2024-01-10 10:49:36.069089: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-10 10:49:36.942023: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
1021 / 118287 images have no annotations
calib2017 #4000: /local/shared_with_docker/rskim_model_compiler/datasets/coco/images/train2017/000000088376.jpg: 100%|█| 4000/4000 [00:19<00
Done converting 4000 images

However, when I try to run hailomz compile command ... the following error occurs:

> $hailomz compile --ckpt ../models/yolov5m_wo_spp.onnx  --calib-path /local/shared_with_docker/rskim_model_compiler/datasets/coco/images/train2017/ --yaml yolov5m_wo_spp.yaml
Traceback (most recent call last):
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 314, in create_module
    so_path = build_module(spec.name, pyxfilename=spec.origin, pyxbuild_dir=self._pyxbuild_dir,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 197, in build_module
    so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/pyxbuild.py", line 144, in pyx_to_dll
    raise ImportError("reload count for %s reached maximum" % org_path)
ImportError: reload count for /home/hailo/.pyxbld/lib.linux-x86_64-cpython-38/hailo_model_zoo/core/postprocessing/cython_utils/cython_nms.cpython-38-x86_64-linux-gnu.so reached maximum
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/local/workspace/hailo_virtualenv/bin/hailomz", line 33, in <module>
    sys.exit(load_entry_point('hailo-model-zoo', 'console_scripts', 'hailomz')())
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main.py", line 188, in main
    run(args)
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main.py", line 168, in run
    from hailo_model_zoo.main_driver import parse, optimize, compile, profile, evaluate
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main_driver.py", line 14, in <module>
    from hailo_model_zoo.core.main_utils import (compile_model, get_hef_path, get_integrated_postprocessing,
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/main_utils.py", line 8, in <module>
    from hailo_model_zoo.core.eval import eval_factory
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/eval/eval_factory.py", line 9, in <module>
    from hailo_model_zoo.core.eval.instance_segmentation_evaluation import InstanceSegmentationEval
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/eval/instance_segmentation_evaluation.py", line 8, in <module>
    from hailo_model_zoo.core.eval.instance_segmentation_evaluation_utils import (YolactEval,
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/eval/instance_segmentation_evaluation_utils.py", line 4, in <module>
    from hailo_model_zoo.core.postprocessing.instance_segmentation_postprocessing import _sanitize_coordinates
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/postprocessing/instance_segmentation_postprocessing.py", line 8, in <module>
    from hailo_model_zoo.core.postprocessing.cython_utils.cython_nms import nms as cnms
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 332, in create_module
    raise exc.with_traceback(tb)
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 314, in create_module
    so_path = build_module(spec.name, pyxfilename=spec.origin, pyxbuild_dir=self._pyxbuild_dir,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/_pyximport3.py", line 197, in build_module
    so_path = pyxbuild.pyx_to_dll(pyxfilename, extension_mod,
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/pyximport/pyxbuild.py", line 144, in pyx_to_dll
    raise ImportError("reload count for %s reached maximum" % org_path)
ImportError: Building module hailo_model_zoo.core.postprocessing.cython_utils.cython_nms failed: ['ImportError: reload count for /home/hailo/.pyxbld/lib.linux-x86_64-cpython-38/hailo_model_zoo/core/postprocessing/cython_utils/cython_nms.cpython-38-x86_64-linux-gnu.so reached maximum\n']

When I change the number of images to 1, it does not change...

Here is my yaml file:

base:
- base/yolov5.yaml
quantization:
  calib_set:
  - models_files/coco/2023-08-03/coco_calib2017.tfrecord
network:
  network_name: yolov5m_wo_spp
paths:
  alls_script: yolov5m_wo_spp.alls
  network_path:
  - models_files/ObjectDetection/Detection-COCO/yolo/yolov5m/pretrained/2023-04-25/yolov5m_wo_spp.onnx
  url: https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ObjectDetection/Detection-COCO/yolo/yolov5m/pretrained/2023-04-25/yolov5m_wo_spp.zip
parser:
  nodes:
  - images
  - - Conv_283
    - Conv_267
    - Conv_251
postprocessing:
  device_pre_post_layers:
    nms: false
  postprocess_config_file: models_files/ObjectDetection/Detection-COCO/yolo/yolov5m/pretrained/2023-04-25/yolov5m_nms_config.json
  meta_arch: yolo
  hpp: false
info:
  input_shape: 640x640x3
  output_shape: 20x20x255, 40x40x255, 80x80x255
  operations: 52.98G
  parameters: 22.67M
  framework: pytorch
  training_data: coco train2017
  validation_data: coco val2017
  eval_metric: mAP
  full_precision_result: 42.46
  source: https://github.com/ultralytics/yolov5/releases/tag/v2.0
  license_url: https://github.com/ultralytics/yolov5/blob/master/LICENSE

Thank you for your assistance.

**Comment by ryangsookim** [comment]
I'm trying to run the hailomz compile on another server, and i encountered the following errors:

> hailomz compile --ckpt ../models/yolov5m_wo_spp.onnx --calib-path /local/shared_with_docker/rskim_model_compiler/datasets/coco/images/train2017/ --yaml yolov5m_wo_spp.yaml
<Hailo Model Zoo INFO> Start run for network yolov5m_wo_spp ...
<Hailo Model Zoo INFO> Initializing the hailo8 runner...
[info] NMS structure of yolov5 (or equivalent architecture) was detected. Default values of NMS anchors were loaded to NMS config json
[info] A generated NMS config file will be saved inside the har. To add NMS postprocessing to the model, please use the command: nms_postprocess(meta_arch=yolov5).
[info] Translation completed on ONNX model yolov5m_wo_spp
[info] Initialized runner for yolov5m_wo_spp
[info] Saved HAR to: /local/shared_with_docker/rskim_model_compiler/hailomz_test/yolov5m_wo_spp.har
[info] Loading model script to yolov5m_wo_spp from /local/workspace/hailo_model_zoo/hailo_model_zoo/cfg/alls/generic/yolov5m_wo_spp.alls
Traceback (most recent call last):
  File "/local/workspace/hailo_virtualenv/bin/hailomz", line 33, in <module>
    sys.exit(load_entry_point('hailo-model-zoo', 'console_scripts', 'hailomz')())
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main.py", line 188, in main
    run(args)
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main.py", line 177, in run
    return handlers[args.command](args)
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main_driver.py", line 206, in compile
    _ensure_optimized(runner, logger, args, network_info)
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/main_driver.py", line 65, in _ensure_optimized
    optimize_model(runner, logger, network_info, args.calib_path, args.results_dir,
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/main_utils.py", line 228, in optimize_model
    optimize_full_precision_model(runner, model_script=model_script, resize=resize, input_conversion=input_conversion)
  File "/local/workspace/hailo_model_zoo/hailo_model_zoo/core/main_utils.py", line 223, in optimize_full_precision_model
    runner.optimize_full_precision()
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/hailo_sdk_common/states/states.py", line 16, in wrapped_func
    return func(self, *args, **kwargs)
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/hailo_sdk_client/runner/client_runner.py", line 1552, in optimize_full_precision
    self._optimize_full_precision()
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/hailo_sdk_client/runner/client_runner.py", line 1555, in _optimize_full_precision
    self._sdk_backend.optimize_full_precision()
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 1218, in optimize_full_precision
    model, params = self._apply_model_modification_commands(model, params, update_model_and_params)
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/hailo_sdk_client/sdk_backend/sdk_backend.py", line 1150, in _apply_model_modification_commands
    model, params = command.apply(model, params, hw_consts=self.hw_arch.consts)
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/hailo_sdk_client/sdk_backend/script_parser/nms_postprocess_command.py", line 273, in apply
    self._get_config_file_from_path()
  File "/local/workspace/hailo_virtualenv/lib/python3.8/site-packages/hailo_sdk_client/sdk_backend/script_parser/nms_postprocess_command.py", line 398, in _get_config_file_from_path
    raise AllocatorScriptParserException(f"Post-process config file isn't found in {config_path}. "
hailo_sdk_client.sdk_backend.sdk_backend_exceptions.AllocatorScriptParserException: Post-process config file isn't found in /local/shared_with_docker/.hailomz/models_files/ObjectDetection/Detection-COCO/yolo/yolov5m/pretrained/2023-04-25/yolov5m_nms_config.json. Please make sure the given path is relative to the .alls file location, or it is a global path.

How can i get the "yolov5m_nms_config.json" file..?

**Comment by ryangsookim** [comment]
Hi, 

When I restart the sw_suite_docker, the following warnings are encountered

rskim@rskim:/mnt/storage/HAILO/sw_suite_2023-10$ bash hailo_ai_sw_suite_docker_run.sh 
Starting new container
Running Hailo AI SW suite Docker image with the folowing Docker command:
docker run --privileged --net=host -e DISPLAY=:0 -e XDG_RUNTIME_DIR=/run/user/1000 --device=/dev/dri:/dev/dri --ipc=host --group-add 44 -v /dev:/dev -v /lib/firmware:/lib/firmware -v /lib/modules:/lib/modules -v /lib/udev/rules.d:/lib/udev/rules.d -v /usr/src:/usr/src -v /tmp/hailo_docker.xauth:/home/hailo/.Xauthority -v /tmp/.X11-unix/:/tmp/.X11-unix/ --name hailo_ai_sw_suite_2023-10_container -v /var/run/docker.sock:/var/run/docker.sock -v /etc/machine-id:/etc/machine-id:ro -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket -v /mnt/storage/HAILO/sw_suite_2023-10/shared_with_docker/:/local/shared_with_docker:rw -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro -v /var/lib/dkms:/var/lib/dkms -ti hailo_ai_sw_suite_2023-10:1

==========
== CUDA ==
==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

**Comment by nina-vilela** [comment]
@ryangsookim 

I would just like to confirm that your first problem is fixed. You could successfully compile yolov5m_wo_spp, right?

For your other questions, since it does not relate to the ModelZoo, we would be happy to assist you through our ticketing system instead. Please open a ticket [here. ](https://developer.hailo.ai/contact-customer-support/)

**Comment by ryangsookim** [comment]
@nina-vilela 

My first problem was fixed.

Are there any method for creating a calib.tfrecord file from a custom YOLO dataset, specifically without utilizing an instances.json file. ??

**Comment by nina-vilela** [comment]
@ryangsookim 

You can use [this script.](https://github.com/hailo-ai/hailo_model_zoo/blob/master/hailo_model_zoo/datasets/create_coco_tfrecord.py)

We couldn't find a ticket for your issue with the yolo_general_inference example. Please let us know if you need any help with permissions for opening one.

**Comment by pcycccccc** [comment]
@nina-vilela 
Hello, May I ask if this script is directly invoked? What is the format of the dataset I need to prepare before calling it? Images and labels? What is the format of the tags? I'm a little vague about that

**Comment by tmyapple** [comment]
@pcycccccc you can find reference for how to use this script in the following [data documentation](https://github.com/hailo-ai/hailo_model_zoo/blob/master/docs/DATA.rst#coco2017)
