### ISSUE TITLE
YOLOV8s error compile

### ISSUE THREAD

**Issue by m4syuka** [hailo-ai/hailo_model_zoo#89]
`hailomz compile --ckpt /content/best.onnx --calib-path /content/images/ --yaml /content/yolov8s.yaml`

output:
```
Traceback (most recent call last):
  File "/usr/local/bin/hailomz", line 33, in <module>
    sys.exit(load_entry_point('hailo-model-zoo', 'console_scripts', 'hailomz')())
  File "/content/hailo_model_zoo/hailo_model_zoo/main.py", line 190, in main
    run(args)
  File "/content/hailo_model_zoo/hailo_model_zoo/main.py", line 170, in run
    from hailo_model_zoo.main_driver import parse, optimize, compile, profile, evaluate
  File "/content/hailo_model_zoo/hailo_model_zoo/main_driver.py", line 13, in <module>
    from hailo_model_zoo.core.main_utils import (compile_model, get_hef_path, get_integrated_postprocessing,
  File "/content/hailo_model_zoo/hailo_model_zoo/core/main_utils.py", line 8, in <module>
    from hailo_model_zoo.core.eval import eval_factory
  File "/content/hailo_model_zoo/hailo_model_zoo/core/eval/eval_factory.py", line 26, in <module>
    from hailo_model_zoo.core.eval.image_generation_from_text_evaluation import ImagegenerationFromTextEval
  File "/content/hailo_model_zoo/hailo_model_zoo/core/eval/image_generation_from_text_evaluation.py", line 5, in <module>
    from torchmetrics.multimodal.clip_score import CLIPScore
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 50, in <module>
    from torchmetrics.functional.image._deprecated import (
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/image/__init__.py", line 17, in <module>
    from torchmetrics.functional.image.lpips import learned_perceptual_image_patch_similarity
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/image/lpips.py", line 45, in <module>
    from torchvision import models as tv
  File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py", line 4, in <module>
    import torch._custom_ops
ModuleNotFoundError: No module named 'torch._custom_ops'
```
how to solve this problem?

ps. use google colab

**Comment by omerwer** [comment]
Hi @m4syuka,
Is best.onnx a standard yolov8 model of a custom one? what is the version of torch you are using?
I believe it may be connected to the use in Google Colab. Does the same error happens when you run it in a virtual env with the Hailo Model Zoo packages installed to it?

Regards,
